"""Bulk WiFi import file parsing: JSON list/map, CSV/TSV (incl. quoted
delimiter fields), wpa_supplicant.conf blocks, and the shared skip/error
rules (blank/# lines, malformed rows, empty/unreadable files)."""

import pytest

from buddy_bridge.wifi_import import WifiImportError, parse_wifi_import_file


def _write(tmp_path, name, text):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


# ---- JSON ----


def test_json_list_of_objects(tmp_path):
    path = _write(
        tmp_path,
        "wifi.json",
        '[{"ssid": "HomeNet", "pass": "s3cr3t!"}, {"ssid": "Office", "pass": "hunter2"}]',
    )
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert warnings == []


def test_json_ssid_password_map(tmp_path):
    path = _write(tmp_path, "wifi.json", '{"HomeNet": "s3cr3t!", "Office": "hunter2"}')
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert warnings == []


def test_json_list_preserves_file_order(tmp_path):
    path = _write(
        tmp_path,
        "wifi.json",
        '[{"ssid": "Z", "pass": "1"}, {"ssid": "A", "pass": "2"}, {"ssid": "M", "pass": "3"}]',
    )
    entries, _ = parse_wifi_import_file(path)
    assert [ssid for ssid, _ in entries] == ["Z", "A", "M"]


def test_json_list_skips_malformed_entries_with_warning(tmp_path):
    path = _write(
        tmp_path,
        "wifi.json",
        '[{"ssid": "Good", "pass": "pw"}, {"ssid": "NoPass"}, "not-an-object", 42]',
    )
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("Good", "pw")]
    assert len(warnings) == 3
    assert "NoPass" in warnings[0]
    assert "entry 2" in warnings[1]
    assert "entry 3" in warnings[2]


def test_json_scalar_top_level_is_a_hard_error(tmp_path):
    path = _write(tmp_path, "wifi.json", "42")
    with pytest.raises(WifiImportError, match="list.*object|object.*list"):
        parse_wifi_import_file(path)


def test_json_password_key_alias_accepted(tmp_path):
    # "password" is accepted alongside the spec's "pass" key.
    path = _write(tmp_path, "wifi.json", '[{"ssid": "HomeNet", "password": "s3cr3t!"}]')
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!")]
    assert warnings == []


# ---- CSV / TSV ----


def test_csv_basic(tmp_path):
    path = _write(tmp_path, "wifi.csv", "HomeNet,s3cr3t!\nOffice,hunter2\n")
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert warnings == []


def test_csv_skips_blank_lines_and_comments(tmp_path):
    path = _write(
        tmp_path,
        "wifi.csv",
        "# my networks\nHomeNet,s3cr3t!\n\n  \n# a trailing comment\nOffice,hunter2\n",
    )
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert warnings == []


def test_csv_quoted_field_with_embedded_comma(tmp_path):
    path = _write(
        tmp_path,
        "wifi.csv",
        'HomeNet,s3cr3t!\n"My, Home Net","p@ss,word"\n',
    )
    entries, _ = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("My, Home Net", "p@ss,word")]


def test_tsv_basic(tmp_path):
    path = _write(tmp_path, "wifi.tsv", "HomeNet\ts3cr3t!\nOffice\thunter2\n")
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert warnings == []


def test_csv_malformed_row_skipped_with_warning(tmp_path):
    path = _write(tmp_path, "wifi.csv", "HomeNet,s3cr3t!\njust-one-field\nOffice,hunter2\n")
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2")]
    assert len(warnings) == 1
    assert "line 2" in warnings[0]


def test_csv_row_with_no_data_lines_returns_empty_not_error(tmp_path):
    path = _write(tmp_path, "wifi.csv", "# nothing but comments\n\n# more comments\n")
    entries, warnings = parse_wifi_import_file(path)
    assert entries == []
    assert warnings == []


# ---- wpa_supplicant.conf ----


_WPA_SAMPLE = """\
# generated by wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="HomeNet"
    psk="s3cr3t!"
    key_mgmt=WPA-PSK
}

network={
    ssid="Office"
    psk="hunter2000"
}
"""


def test_wpa_supplicant_extracts_ssid_and_psk(tmp_path):
    path = _write(tmp_path, "wpa_supplicant.conf", _WPA_SAMPLE)
    entries, warnings = parse_wifi_import_file(path)
    assert entries == [("HomeNet", "s3cr3t!"), ("Office", "hunter2000")]
    assert warnings == []


def test_wpa_supplicant_unescapes_quoted_psk(tmp_path):
    path = _write(
        tmp_path,
        "wpa_supplicant.conf",
        'network={\n    ssid="Home\\"Net"\n    psk="p\\\\w"\n}\n',
    )
    entries, _ = parse_wifi_import_file(path)
    assert entries == [('Home"Net', "p\\w")]


def test_wpa_supplicant_skips_raw_hex_psk(tmp_path):
    hex_psk = "a" * 64
    path = _write(
        tmp_path,
        "wpa_supplicant.conf",
        f'network={{\n    ssid="HomeNet"\n    psk={hex_psk}\n}}\n',
    )
    entries, warnings = parse_wifi_import_file(path)
    assert entries == []
    assert len(warnings) == 1
    assert "raw-hex" in warnings[0]
    assert "HomeNet" in warnings[0]


def test_wpa_supplicant_skips_open_network_no_psk(tmp_path):
    path = _write(
        tmp_path, "wpa_supplicant.conf", 'network={\n    ssid="OpenGuest"\n    key_mgmt=NONE\n}\n'
    )
    entries, warnings = parse_wifi_import_file(path)
    assert entries == []
    assert "OpenGuest" in warnings[0]


# ---- errors: unreadable / empty / malformed ----


def test_missing_file_is_a_clear_error(tmp_path):
    with pytest.raises(WifiImportError, match="not found"):
        parse_wifi_import_file(tmp_path / "does-not-exist.json")


def test_empty_file_is_a_clear_error(tmp_path):
    path = _write(tmp_path, "wifi.json", "")
    with pytest.raises(WifiImportError, match="empty"):
        parse_wifi_import_file(path)


def test_whitespace_only_file_is_a_clear_error(tmp_path):
    path = _write(tmp_path, "wifi.json", "   \n\n  \t \n")
    with pytest.raises(WifiImportError, match="empty"):
        parse_wifi_import_file(path)


def test_garbage_text_does_not_crash_and_yields_no_entries(tmp_path):
    # Not valid JSON, not wpa_supplicant, and no delimiter on any line: every
    # line is a malformed CSV row (skipped + warned), never a traceback.
    path = _write(tmp_path, "wifi.txt", "this is not wifi data\njust some prose\n")
    entries, warnings = parse_wifi_import_file(path)
    assert entries == []
    assert len(warnings) == 2


def test_directory_instead_of_file_is_a_clear_error(tmp_path):
    with pytest.raises(WifiImportError):
        parse_wifi_import_file(tmp_path)
